name: Deploy React App to Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 109.205.179.181
        username: root
        password: AVstore123#
        script: |
            cd /var/www/av-dynamic-web/dynamic-av-web
            git fetch origin
            git reset --hard origin/main
            docker build --no-cache -t av-dynamic-frontend .
            docker rm -f av-dynamic-frontend-container 2>/dev/null || true
            docker run -d \
              --restart always \
              -p 3005:80 \
              --name av-dynamic-frontend-container \
              av-dynamic-frontend

